window.taiData = (() => {
  const rawVocabData = [
    { id: 1, thai: "สวัสดี", pinyin: "sa-wat-dee", meaning: "你好", category: "問候" },
    { id: 2, thai: "ขอบคุณ", pinyin: "khop-khun", meaning: "謝謝", category: "問候" },
    { id: 3, thai: "ขอโทษ", pinyin: "kho-thot", meaning: "對不起", category: "問候" },
    { id: 4, thai: "ไม่เป็นไร", pinyin: "mai pen rai", meaning: "沒關係", category: "常用" },
    { id: 5, thai: "ใช่", pinyin: "chai", meaning: "是/對", category: "常用" },
    { id: 6, thai: "ไม่", pinyin: "mai", meaning: "不/沒有", category: "常用" },
    { id: 7, thai: "ผม", pinyin: "phom", meaning: "我 (男)", category: "代詞" },
    { id: 8, thai: "ฉัน", pinyin: "chan", meaning: "我 (女)", category: "代詞" },
    { id: 9, thai: "คุณ", pinyin: "khun", meaning: "你", category: "代詞" },
    { id: 10, thai: "เขา", pinyin: "khao", meaning: "他/她", category: "代詞" },
    { id: 11, thai: "อะไร", pinyin: "a-rai", meaning: "什麼", category: "疑問" },
    { id: 12, thai: "ที่ไหน", pinyin: "tee nai", meaning: "在哪裡", category: "疑問" },
    { id: 13, thai: "เมื่อไหร่", pinyin: "muea rai", meaning: "什麼時候", category: "疑問" },
    { id: 14, thai: "เท่าไหร่", pinyin: "thao-rai", meaning: "多少錢", category: "疑問" },
    { id: 15, thai: "ใคร", pinyin: "khrai", meaning: "誰", category: "疑問" },
    { id: 16, thai: "กิน", pinyin: "gin", meaning: "吃", category: "動詞" },
    { id: 17, thai: "ดื่ม", pinyin: "duem", meaning: "喝", category: "動詞" },
    { id: 18, thai: "ไป", pinyin: "pai", meaning: "去", category: "動詞" },
    { id: 19, thai: "มา", pinyin: "ma", meaning: "來", category: "動詞" },
    { id: 20, thai: "ชอบ", pinyin: "chob", meaning: "喜歡", category: "動詞" },
    { id: 21, thai: "รัก", pinyin: "rak", meaning: "愛", category: "動詞" },
    { id: 22, thai: "ทำ", pinyin: "tham", meaning: "做", category: "動詞" },
    { id: 23, thai: "ดู", pinyin: "du", meaning: "看", category: "動詞" },
    { id: 24, thai: "ฟัง", pinyin: "fang", meaning: "聽", category: "動詞" },
    { id: 25, thai: "พูด", pinyin: "phut", meaning: "說", category: "動詞" },
    { id: 26, thai: "นอน", pinyin: "non", meaning: "睡覺", category: "動詞" },
    { id: 27, thai: "เอา", pinyin: "ao", meaning: "要 (物品)", category: "動詞" },
    { id: 28, thai: "บ้าน", pinyin: "baan", meaning: "家", category: "地點" },
    { id: 29, thai: "โรงเรียน", pinyin: "rong-rian", meaning: "學校", category: "地點" },
    { id: 30, thai: "ห้องน้ำ", pinyin: "hong nam", meaning: "洗手間", category: "地點" },
    { id: 31, thai: "ร้านอาหาร", pinyin: "ran a-han", meaning: "餐廳", category: "地點" },
    { id: 32, thai: "น้ำ", pinyin: "nam", meaning: "水", category: "飲食" },
    { id: 33, thai: "ข้าว", pinyin: "khao", meaning: "飯", category: "飲食" },
    { id: 34, thai: "เงิน", pinyin: "ngoen", meaning: "錢", category: "物品" },
    { id: 35, thai: "งาน", pinyin: "ngan", meaning: "工作", category: "物品" },
    { id: 36, thai: "สวย", pinyin: "suay", meaning: "漂亮", category: "形容" },
    { id: 37, thai: "อร่อย", pinyin: "a-roi", meaning: "好吃", category: "形容" },
    { id: 38, thai: "ร้อน", pinyin: "ron", meaning: "熱", category: "形容" },
    { id: 39, thai: "หนาว", pinyin: "nao", meaning: "冷", category: "形容" },
    { id: 40, thai: "ใหญ่", pinyin: "yai", meaning: "大", category: "形容" },
    { id: 41, thai: "เล็ก", pinyin: "lek", meaning: "小", category: "形容" },
    { id: 42, thai: "เผ็ด", pinyin: "phet", meaning: "辣", category: "形容" },
    { id: 43, thai: "หนึ่ง", pinyin: "nueng", meaning: "一 (1)", category: "數字" },
    { id: 44, thai: "สอง", pinyin: "song", meaning: "二 (2)", category: "數字" },
    { id: 45, thai: "สาม", pinyin: "sam", meaning: "三 (3)", category: "數字" },
    { id: 46, thai: "สี่", pinyin: "si", meaning: "四 (4)", category: "數字" },
    { id: 47, thai: "ห้า", pinyin: "ha", meaning: "五 (5)", category: "數字" },
    { id: 48, thai: "สิบ", pinyin: "sip", meaning: "十 (10)", category: "數字" },
    { id: 49, thai: "ร้อย", pinyin: "roi", meaning: "百 (100)", category: "數字" },
    { id: 50, thai: "วันนี้", pinyin: "wan-nee", meaning: "今天", category: "時間" },
    { id: 51, thai: "พรุ่งนี้", pinyin: "phrung-ni", meaning: "明天", category: "時間" },
    { id: 52, thai: "เมื่อวาน", pinyin: "muea-wan", meaning: "昨天", category: "時間" },
    { id: 53, thai: "ตอนนี้", pinyin: "ton-ni", meaning: "現在", category: "時間" },
    { id: 54, thai: "เร็ว", pinyin: "reo", meaning: "快", category: "副詞" },
    { id: 55, thai: "ช้า", pinyin: "cha", meaning: "慢", category: "副詞" },
    { id: 56, thai: "สนุก", pinyin: "sa-nuk", meaning: "好玩", category: "情緒" },
    { id: 57, thai: "เบื่อ", pinyin: "beua", meaning: "無聊", category: "情緒" },
    { id: 58, thai: "หิว", pinyin: "hiu", meaning: "餓", category: "感覺" },
    { id: 59, thai: "กระหายน้ำ", pinyin: "kra-hai-nam", meaning: "渴", category: "感覺" },
    { id: 60, thai: "เจ็บ", pinyin: "jep", meaning: "痛", category: "感覺" },
    { id: 61, thai: "สุขภาพ", pinyin: "suk-kha-phaap", meaning: "健康", category: "名詞" },
    { id: 62, thai: "โรงพยาบาล", pinyin: "rong-pha-yaa-baan", meaning: "醫院", category: "地點" },
    { id: 63, thai: "ร้านกาแฟ", pinyin: "ran-ga-fae", meaning: "咖啡店", category: "地點" },
    { id: 64, thai: "ตลาด", pinyin: "ta-lat", meaning: "市場", category: "地點" },
    { id: 65, thai: "สนามบิน", pinyin: "sa-nam-bin", meaning: "機場", category: "地點" },
    { id: 66, thai: "รถไฟฟ้า", pinyin: "rot-fai-faa", meaning: "捷運", category: "交通" },
    { id: 67, thai: "แท็กซี่", pinyin: "thaek-si", meaning: "計程車", category: "交通" },
    { id: 68, thai: "รถเมล์", pinyin: "rot-me", meaning: "公車", category: "交通" },
    { id: 69, thai: "รถไฟ", pinyin: "rot-fai", meaning: "火車", category: "交通" },
    { id: 70, thai: "จักรยาน", pinyin: "jak-kra-yaan", meaning: "腳踏車", category: "交通" },
    { id: 71, thai: "เสื้อ", pinyin: "seua", meaning: "衣服", category: "服飾" },
    { id: 72, thai: "กางเกง", pinyin: "kang-keng", meaning: "褲子", category: "服飾" },
    { id: 73, thai: "รองเท้า", pinyin: "rong-thao", meaning: "鞋子", category: "服飾" },
    { id: 74, thai: "หมวก", pinyin: "muak", meaning: "帽子", category: "服飾" },
    { id: 75, thai: "กระเป๋า", pinyin: "kra-pao", meaning: "包包", category: "物品" },
    { id: 76, thai: "หนังสือ", pinyin: "nang-seu", meaning: "書", category: "物品" },
    { id: 77, thai: "ปากกา", pinyin: "pak-kaa", meaning: "筆", category: "物品" },
    { id: 78, thai: "สมุด", pinyin: "sa-mut", meaning: "筆記本", category: "物品" },
    { id: 79, thai: "โทรศัพท์", pinyin: "tho-ra-sap", meaning: "電話", category: "物品" },
    { id: 80, thai: "คอมพิวเตอร์", pinyin: "khom-phiu-toe", meaning: "電腦", category: "物品" },
    { id: 81, thai: "อาหารเช้า", pinyin: "a-han-chao", meaning: "早餐", category: "飲食" },
    { id: 82, thai: "อาหารกลางวัน", pinyin: "a-han-klang-wan", meaning: "午餐", category: "飲食" },
    { id: 83, thai: "อาหารเย็น", pinyin: "a-han-yen", meaning: "晚餐", category: "飲食" },
    { id: 84, thai: "ขนม", pinyin: "kha-nom", meaning: "點心", category: "飲食" },
    { id: 85, thai: "กาแฟ", pinyin: "ga-fae", meaning: "咖啡", category: "飲品" },
    { id: 86, thai: "ชา", pinyin: "cha", meaning: "茶", category: "飲品" },
    { id: 87, thai: "น้ำผลไม้", pinyin: "nam-phon-la-mai", meaning: "果汁", category: "飲品" },
    { id: 88, thai: "เบียร์", pinyin: "bia", meaning: "啤酒", category: "飲品" },
    { id: 89, thai: "หวาน", pinyin: "wan", meaning: "甜", category: "形容" },
    { id: 90, thai: "เค็ม", pinyin: "khem", meaning: "鹹", category: "形容" },
    { id: 91, thai: "เปรี้ยว", pinyin: "priao", meaning: "酸", category: "形容" },
    { id: 92, thai: "ขม", pinyin: "khom", meaning: "苦", category: "形容" },
    { id: 93, thai: "สั้น", pinyin: "san", meaning: "短", category: "形容" },
    { id: 94, thai: "ยาว", pinyin: "yao", meaning: "長", category: "形容" },
    { id: 95, thai: "หนัก", pinyin: "nak", meaning: "重", category: "形容" },
    { id: 96, thai: "เบา", pinyin: "bao", meaning: "輕", category: "形容" },
    { id: 97, thai: "แพง", pinyin: "phaeng", meaning: "貴", category: "形容" },
    { id: 98, thai: "ถูก", pinyin: "thuk", meaning: "便宜", category: "形容" },
    { id: 99, thai: "เพื่อน", pinyin: "pheuan", meaning: "朋友", category: "人物" },
    { id: 100, thai: "ครอบครัว", pinyin: "khrop-khrua", meaning: "家庭", category: "人物" },
    { id: 101, thai: "ศูนย์", pinyin: "suun", meaning: "零", category: "數字" },
    { id: 102, thai: "หก", pinyin: "hok", meaning: "六 (6)", category: "數字" },
    { id: 103, thai: "เจ็ด", pinyin: "jet", meaning: "七 (7)", category: "數字" },
    { id: 104, thai: "แปด", pinyin: "paet", meaning: "八 (8)", category: "數字" },
    { id: 105, thai: "เก้า", pinyin: "kao", meaning: "九 (9)", category: "數字" },
    { id: 106, thai: "สิบเอ็ด", pinyin: "sip-et", meaning: "十一", category: "數字" },
    { id: 107, thai: "สิบสอง", pinyin: "sip-song", meaning: "十二", category: "數字" },
    { id: 108, thai: "สิบสาม", pinyin: "sip-sam", meaning: "十三", category: "數字" },
    { id: 109, thai: "สิบสี่", pinyin: "sip-si", meaning: "十四", category: "數字" },
    { id: 110, thai: "สิบห้า", pinyin: "sip-ha", meaning: "十五", category: "數字" },
    { id: 111, thai: "สิบหก", pinyin: "sip-hok", meaning: "十六", category: "數字" },
    { id: 112, thai: "สิบเจ็ด", pinyin: "sip-jet", meaning: "十七", category: "數字" },
    { id: 113, thai: "สิบแปด", pinyin: "sip-paet", meaning: "十八", category: "數字" },
    { id: 114, thai: "สิบเก้า", pinyin: "sip-kao", meaning: "十九", category: "數字" },
    { id: 115, thai: "ยี่สิบ", pinyin: "yee-sip", meaning: "二十", category: "數字" },
    { id: 116, thai: "ยี่สิบเอ็ด", pinyin: "yee-sip-et", meaning: "二十一", category: "數字" },
    { id: 117, thai: "ยี่สิบสอง", pinyin: "yee-sip-song", meaning: "二十二", category: "數字" },
    { id: 118, thai: "สามสิบ", pinyin: "sam-sip", meaning: "三十", category: "數字" },
    { id: 119, thai: "สี่สิบ", pinyin: "si-sip", meaning: "四十", category: "數字" },
    { id: 120, thai: "ห้าสิบ", pinyin: "ha-sip", meaning: "五十", category: "數字" },
    { id: 121, thai: "หกสิบ", pinyin: "hok-sip", meaning: "六十", category: "數字" },
    { id: 122, thai: "เจ็ดสิบ", pinyin: "jet-sip", meaning: "七十", category: "數字" },
    { id: 123, thai: "แปดสิบ", pinyin: "paet-sip", meaning: "八十", category: "數字" },
    { id: 124, thai: "เก้าสิบ", pinyin: "kao-sip", meaning: "九十", category: "數字" },
    { id: 125, thai: "หนึ่งพัน", pinyin: "nueng-phan", meaning: "一千", category: "數字" },
    { id: 126, thai: "หมื่น", pinyin: "muen", meaning: "一萬", category: "數字" },
    { id: 127, thai: "แสน", pinyin: "saen", meaning: "十萬", category: "數字" },
    { id: 128, thai: "ล้าน", pinyin: "laan", meaning: "一百萬", category: "數字" },
    { id: 129, thai: "วันจันทร์", pinyin: "wan-jan", meaning: "星期一", category: "時間" },
    { id: 130, thai: "วันอังคาร", pinyin: "wan-ang-khan", meaning: "星期二", category: "時間" },
    { id: 131, thai: "วันพุธ", pinyin: "wan-phut", meaning: "星期三", category: "時間" },
    { id: 132, thai: "วันพฤหัสบดี", pinyin: "wan-pa-rue-hat", meaning: "星期四", category: "時間" },
    { id: 133, thai: "วันศุกร์", pinyin: "wan-suk", meaning: "星期五", category: "時間" },
    { id: 134, thai: "วันเสาร์", pinyin: "wan-sao", meaning: "星期六", category: "時間" },
    { id: 135, thai: "วันอาทิตย์", pinyin: "wan-aa-thit", meaning: "星期日", category: "時間" },
    { id: 136, thai: "เช้า", pinyin: "chao", meaning: "早上", category: "時間" },
    { id: 137, thai: "บ่าย", pinyin: "baai", meaning: "下午", category: "時間" },
    { id: 138, thai: "เย็น", pinyin: "yen", meaning: "傍晚", category: "時間" },
    { id: 139, thai: "กลางคืน", pinyin: "klang-khuen", meaning: "夜晚", category: "時間" },
    { id: 140, thai: "ฤดูร้อน", pinyin: "rue-du-ron", meaning: "夏天", category: "季節" },
    { id: 141, thai: "ฤดูฝน", pinyin: "rue-du-fon", meaning: "雨季", category: "季節" },
    { id: 142, thai: "ฤดูหนาว", pinyin: "rue-du-nao", meaning: "冬天", category: "季節" },
    { id: 143, thai: "ฤดูใบไม้ผลิ", pinyin: "rue-du-bai-mai-pli", meaning: "春天", category: "季節" },
    { id: 144, thai: "ฤดูใบไม้ร่วง", pinyin: "rue-du-bai-mai-ruang", meaning: "秋天", category: "季節" },
    { id: 145, thai: "มกราคม", pinyin: "mok-kha-raa-kom", meaning: "一月", category: "月份" },
    { id: 146, thai: "กุมภาพันธ์", pinyin: "kum-phaa-phan", meaning: "二月", category: "月份" },
    { id: 147, thai: "มีนาคม", pinyin: "mee-naa-kom", meaning: "三月", category: "月份" },
    { id: 148, thai: "เมษายน", pinyin: "mae-sa-yon", meaning: "四月", category: "月份" },
    { id: 149, thai: "พฤษภาคม", pinyin: "phreut-sa-phaa-kom", meaning: "五月", category: "月份" },
    { id: 150, thai: "มิถุนายน", pinyin: "mi-thu-naa-yon", meaning: "六月", category: "月份" },
    { id: 151, thai: "กรกฎาคม", pinyin: "ka-ra-ka-daa-kom", meaning: "七月", category: "月份" },
    { id: 152, thai: "สิงหาคม", pinyin: "sing-haa-kom", meaning: "八月", category: "月份" },
    { id: 153, thai: "กันยายน", pinyin: "kan-yaa-yon", meaning: "九月", category: "月份" },
    { id: 154, thai: "ตุลาคม", pinyin: "tu-laa-kom", meaning: "十月", category: "月份" },
    { id: 155, thai: "พฤศจิกายน", pinyin: "phreut-sa-ji-gaa-yon", meaning: "十一月", category: "月份" },
    { id: 156, thai: "ธันวาคม", pinyin: "than-waa-kom", meaning: "十二月", category: "月份" },
    { id: 157, thai: "แดง", pinyin: "daeng", meaning: "紅色", category: "顏色" },
    { id: 158, thai: "น้ำเงิน", pinyin: "nam-ngern", meaning: "藍色", category: "顏色" },
    { id: 159, thai: "เขียว", pinyin: "khieow", meaning: "綠色", category: "顏色" },
    { id: 160, thai: "เหลือง", pinyin: "lueang", meaning: "黃色", category: "顏色" },
    { id: 161, thai: "ม่วง", pinyin: "muang", meaning: "紫色", category: "顏色" },
    { id: 162, thai: "ชมพู", pinyin: "chom-phu", meaning: "粉紅", category: "顏色" },
    { id: 163, thai: "ดำ", pinyin: "dam", meaning: "黑色", category: "顏色" },
    { id: 164, thai: "ขาว", pinyin: "khao", meaning: "白色", category: "顏色" },
    { id: 165, thai: "น้ำตาล", pinyin: "nam-tan", meaning: "棕色", category: "顏色" },
    { id: 166, thai: "เทา", pinyin: "thao", meaning: "灰色", category: "顏色" },
    { id: 167, thai: "ทอง", pinyin: "thong", meaning: "金色", category: "顏色" },
    { id: 168, thai: "ส้ม", pinyin: "som", meaning: "橘色", category: "顏色" },
    { id: 169, thai: "สุนัข", pinyin: "su-nak", meaning: "狗", category: "動物" },
    { id: 170, thai: "แมว", pinyin: "maeo", meaning: "貓", category: "動物" },
    { id: 171, thai: "ช้าง", pinyin: "chaang", meaning: "大象", category: "動物" },
    { id: 172, thai: "ม้า", pinyin: "maa", meaning: "馬", category: "動物" },
    { id: 173, thai: "วัว", pinyin: "wua", meaning: "牛", category: "動物" },
    { id: 174, thai: "ควาย", pinyin: "khwaai", meaning: "水牛", category: "動物" },
    { id: 175, thai: "หมู", pinyin: "muu", meaning: "豬", category: "動物" },
    { id: 176, thai: "ไก่", pinyin: "gai", meaning: "雞", category: "動物" },
    { id: 177, thai: "เป็ด", pinyin: "ped", meaning: "鴨", category: "動物" },
    { id: 178, thai: "ห่าน", pinyin: "haan", meaning: "鵝", category: "動物" },
    { id: 179, thai: "ปลา", pinyin: "plaa", meaning: "魚", category: "動物" },
    { id: 180, thai: "กุ้ง", pinyin: "gung", meaning: "蝦", category: "動物" },
    { id: 181, thai: "ปู", pinyin: "puu", meaning: "螃蟹", category: "動物" },
    { id: 182, thai: "ปลาหมึก", pinyin: "plaa-muek", meaning: "花枝", category: "動物" },
    { id: 183, thai: "ปลาฉลาม", pinyin: "plaa-cha-laam", meaning: "鯊魚", category: "動物" },
    { id: 184, thai: "ปลากระเบน", pinyin: "plaa-kra-ben", meaning: "魟魚", category: "動物" },
    { id: 185, thai: "เต่า", pinyin: "tao", meaning: "烏龜", category: "動物" },
    { id: 186, thai: "งู", pinyin: "nguu", meaning: "蛇", category: "動物" },
    { id: 187, thai: "ลิง", pinyin: "ling", meaning: "猴子", category: "動物" },
    { id: 188, thai: "เสือ", pinyin: "seua", meaning: "老虎", category: "動物" },
    { id: 189, thai: "สิงโต", pinyin: "sing-to", meaning: "獅子", category: "動物" },
    { id: 190, thai: "หมี", pinyin: "mee", meaning: "熊", category: "動物" },
    { id: 191, thai: "หมาป่า", pinyin: "maa-paa", meaning: "狼", category: "動物" },
    { id: 192, thai: "จิ้งจอก", pinyin: "jing-jok", meaning: "狐狸", category: "動物" },
    { id: 193, thai: "กระต่าย", pinyin: "kra-taai", meaning: "兔子", category: "動物" },
    { id: 194, thai: "แพะ", pinyin: "phae", meaning: "山羊", category: "動物" },
    { id: 195, thai: "แกะ", pinyin: "gae", meaning: "綿羊", category: "動物" },
    { id: 196, thai: "กวาง", pinyin: "kwang", meaning: "鹿", category: "動物" },
    { id: 197, thai: "นก", pinyin: "nok", meaning: "鳥", category: "動物" },
    { id: 198, thai: "นกฮูก", pinyin: "nok-hook", meaning: "貓頭鷹", category: "動物" },
    { id: 199, thai: "ผีเสื้อ", pinyin: "phi-seua", meaning: "蝴蝶", category: "動物" },
    { id: 200, thai: "แมลงวัน", pinyin: "ma-laeng-wan", meaning: "蒼蠅", category: "動物" },
    { id: 201, thai: "ยุง", pinyin: "yung", meaning: "蚊子", category: "動物" },
    { id: 202, thai: "มด", pinyin: "mot", meaning: "螞蟻", category: "動物" },
    { id: 203, thai: "แมงมุม", pinyin: "maeng-mum", meaning: "蜘蛛", category: "動物" },
    { id: 204, thai: "จระเข้", pinyin: "jo-ra-khe", meaning: "鱷魚", category: "動物" },
    { id: 205, thai: "ฮิปโปโปเตมัส", pinyin: "hip-po-po-te-mat", meaning: "河馬", category: "動物" },
    { id: 206, thai: "จิงโจ้", pinyin: "jing-jo", meaning: "袋鼠", category: "動物" },
    { id: 207, thai: "เพนกวิน", pinyin: "pen-gwin", meaning: "企鵝", category: "動物" },
    { id: 208, thai: "มะม่วง", pinyin: "ma-muang", meaning: "芒果", category: "水果" },
    { id: 209, thai: "กล้วย", pinyin: "kluai", meaning: "香蕉", category: "水果" },
    { id: 210, thai: "สับปะรด", pinyin: "sap-pa-rot", meaning: "鳳梨", category: "水果" },
    { id: 211, thai: "แตงโม", pinyin: "taeng-mo", meaning: "西瓜", category: "水果" },
    { id: 212, thai: "ลิ้นจี่", pinyin: "lin-jee", meaning: "荔枝", category: "水果" },
    { id: 213, thai: "ทุเรียน", pinyin: "thu-rian", meaning: "榴槤", category: "水果" },
    { id: 214, thai: "เงาะ", pinyin: "ngo", meaning: "紅毛丹", category: "水果" },
    { id: 215, thai: "ฝรั่ง", pinyin: "fa-rang", meaning: "芭樂", category: "水果" },
    { id: 216, thai: "แอปเปิล", pinyin: "aep-pil", meaning: "蘋果", category: "水果" },
    { id: 217, thai: "ส้มโอ", pinyin: "som-o", meaning: "文旦", category: "水果" },
    { id: 218, thai: "มะนาว", pinyin: "ma-nao", meaning: "萊姆", category: "水果" },
    { id: 219, thai: "มะพร้าว", pinyin: "ma-phrao", meaning: "椰子", category: "水果" },
    { id: 220, thai: "องุ่น", pinyin: "a-ngun", meaning: "葡萄", category: "水果" },
    { id: 221, thai: "กีวี", pinyin: "kii-wii", meaning: "奇異果", category: "水果" },
    { id: 222, thai: "เชอร์รี", pinyin: "cher-rii", meaning: "櫻桃", category: "水果" },
    { id: 223, thai: "บลูเบอร์รี", pinyin: "blu-ber-ri", meaning: "藍莓", category: "水果" },
    { id: 224, thai: "สตรอว์เบอร์รี", pinyin: "straw-ber-ri", meaning: "草莓", category: "水果" },
    { id: 225, thai: "มะละกอ", pinyin: "ma-la-kor", meaning: "木瓜", category: "水果" },
    { id: 226, thai: "แคนตาลูป", pinyin: "khaen-ta-loop", meaning: "哈密瓜", category: "水果" },
    { id: 227, thai: "ลูกพีช", pinyin: "luk-peech", meaning: "水蜜桃", category: "水果" },
    { id: 228, thai: "ลูกแพร์", pinyin: "luk-phae", meaning: "梨子", category: "水果" },
    { id: 229, thai: "มังคุด", pinyin: "mang-khut", meaning: "山竹", category: "水果" },
    { id: 230, thai: "ลองกอง", pinyin: "long-gong", meaning: "龍宮果", category: "水果" },
    { id: 231, thai: "เสาวรส", pinyin: "saao-wa-rot", meaning: "百香果", category: "水果" },
    { id: 232, thai: "แก้วมังกร", pinyin: "kaew-mang-kon", meaning: "火龍果", category: "水果" },
    { id: 233, thai: "เมลอน", pinyin: "me-lon", meaning: "蜜瓜", category: "水果" },
    { id: 234, thai: "ลูกพลับ", pinyin: "luk-plap", meaning: "柿子", category: "水果" },
    { id: 235, thai: "ขนุน", pinyin: "kha-nun", meaning: "菠蘿蜜", category: "水果" },
    { id: 236, thai: "ลำไย", pinyin: "lam-yai", meaning: "龍眼", category: "水果" },
    { id: 237, thai: "มะยม", pinyin: "ma-yom", meaning: "泰國醋栗", category: "水果" },
    { id: 238, thai: "มะเขือเทศ", pinyin: "ma-kuea-thet", meaning: "番茄", category: "蔬菜" },
    { id: 239, thai: "แตงกวา", pinyin: "taeng-gwa", meaning: "小黃瓜", category: "蔬菜" },
    { id: 240, thai: "คะน้า", pinyin: "kha-naa", meaning: "芥藍", category: "蔬菜" },
    { id: 241, thai: "กะหล่ำปลี", pinyin: "ka-lam-pli", meaning: "高麗菜", category: "蔬菜" },
    { id: 242, thai: "ผักบุ้ง", pinyin: "phak-bung", meaning: "空心菜", category: "蔬菜" },
    { id: 243, thai: "ผักกาด", pinyin: "phak-kat", meaning: "萵苣", category: "蔬菜" },
    { id: 244, thai: "ผักชี", pinyin: "phak-chee", meaning: "香菜", category: "蔬菜" },
    { id: 245, thai: "โหระพา", pinyin: "ho-ra-pha", meaning: "羅勒", category: "蔬菜" },
    { id: 246, thai: "กะเพรา", pinyin: "ka-phrao", meaning: "打拋葉", category: "蔬菜" },
    { id: 247, thai: "มะเขือยาว", pinyin: "ma-kuea-yao", meaning: "茄子", category: "蔬菜" },
    { id: 248, thai: "แครอท", pinyin: "khae-rot", meaning: "紅蘿蔔", category: "蔬菜" },
    { id: 249, thai: "หอมใหญ่", pinyin: "hom-yai", meaning: "洋蔥", category: "蔬菜" },
    { id: 250, thai: "กระเทียม", pinyin: "kra-thiam", meaning: "大蒜", category: "蔬菜" },
    { id: 251, thai: "ขิง", pinyin: "khing", meaning: "薑", category: "蔬菜" },
    { id: 252, thai: "พริก", pinyin: "phrik", meaning: "辣椒", category: "蔬菜" },
    { id: 253, thai: "มันฝรั่ง", pinyin: "man-fa-rang", meaning: "馬鈴薯", category: "蔬菜" },
    { id: 254, thai: "มันเทศ", pinyin: "man-thet", meaning: "地瓜", category: "蔬菜" },
    { id: 255, thai: "ข้าวโพด", pinyin: "khao-phot", meaning: "玉米", category: "蔬菜" },
    { id: 256, thai: "ถั่วลิสง", pinyin: "thua-li-song", meaning: "花生", category: "蔬菜" },
    { id: 257, thai: "ถั่วเขียว", pinyin: "thua-khieow", meaning: "綠豆", category: "蔬菜" },
    { id: 258, thai: "หน่อไม้", pinyin: "nor-mai", meaning: "竹筍", category: "蔬菜" },
    { id: 259, thai: "เห็ด", pinyin: "het", meaning: "菇類", category: "蔬菜" },
    { id: 260, thai: "ฟักทอง", pinyin: "fak-thong", meaning: "南瓜", category: "蔬菜" },
    { id: 261, thai: "กะหล่ำดอก", pinyin: "ka-lam-dok", meaning: "花椰菜", category: "蔬菜" },
    { id: 262, thai: "บรอกโคลี", pinyin: "brok-kho-lee", meaning: "綠花椰", category: "蔬菜" },
    { id: 263, thai: "บวบ", pinyin: "buap", meaning: "絲瓜", category: "蔬菜" },
    { id: 264, thai: "ครู", pinyin: "khruu", meaning: "老師", category: "職業" },
    { id: 265, thai: "แพทย์", pinyin: "phaet", meaning: "醫生", category: "職業" },
    { id: 266, thai: "พยาบาล", pinyin: "pha-yaa-baan", meaning: "護理師", category: "職業" },
    { id: 267, thai: "วิศวกร", pinyin: "wit-sa-wa-kon", meaning: "工程師", category: "職業" },
    { id: 268, thai: "โปรแกรมเมอร์", pinyin: "pro-gram-mer", meaning: "程式設計師", category: "職業" },
    { id: 269, thai: "ทนายความ", pinyin: "tha-naai-khwam", meaning: "律師", category: "職業" },
    { id: 270, thai: "นักธุรกิจ", pinyin: "nak-thu-ra-kit", meaning: "企業家", category: "職業" },
    { id: 271, thai: "พนักงานขาย", pinyin: "pha-nak-ngan-khaai", meaning: "業務員", category: "職業" },
    { id: 272, thai: "เชฟ", pinyin: "chef", meaning: "主廚", category: "職業" },
    { id: 273, thai: "คนขับรถ", pinyin: "khon-khap-rot", meaning: "司機", category: "職業" },
    { id: 274, thai: "นักบิน", pinyin: "nak-bin", meaning: "飛行員", category: "職業" },
    { id: 275, thai: "พนักงานต้อนรับ", pinyin: "pha-nak-ngan-ton-rap", meaning: "接待員", category: "職業" },
    { id: 276, thai: "ช่างภาพ", pinyin: "chang-phaap", meaning: "攝影師", category: "職業" },
    { id: 277, thai: "ช่างไฟฟ้า", pinyin: "chang-fai-faa", meaning: "電工", category: "職業" },
    { id: 278, thai: "ช่างไม้", pinyin: "chang-mai", meaning: "木工", category: "職業" },
    { id: 279, thai: "เกษตรกร", pinyin: "ka-set-sa-kon", meaning: "農夫", category: "職業" },
    { id: 280, thai: "ชาวประมง", pinyin: "chao-pra-mong", meaning: "漁夫", category: "職業" },
    { id: 281, thai: "ทหาร", pinyin: "tha-han", meaning: "軍人", category: "職業" },
    { id: 282, thai: "ตำรวจ", pinyin: "tam-ruat", meaning: "警察", category: "職業" },
    { id: 283, thai: "นักดนตรี", pinyin: "nak-don-trii", meaning: "樂手", category: "職業" },
    { id: 284, thai: "นักร้อง", pinyin: "nak-rong", meaning: "歌手", category: "職業" },
    { id: 285, thai: "นักเต้น", pinyin: "nak-ten", meaning: "舞者", category: "職業" },
    { id: 286, thai: "นักแสดง", pinyin: "nak-sa-daeng", meaning: "演員", category: "職業" },
    { id: 287, thai: "นักข่าว", pinyin: "nak-khao", meaning: "記者", category: "職業" },
    { id: 288, thai: "นักวิทยาศาสตร์", pinyin: "nak-wit-tha-ya-sat", meaning: "科學家", category: "職業" },
    { id: 289, thai: "นักเขียน", pinyin: "nak-khian", meaning: "作家", category: "職業" },
    { id: 290, thai: "มัคคุเทศก์", pinyin: "mak-khu-thet", meaning: "導遊", category: "職業" },
    { id: 291, thai: "นักออกแบบ", pinyin: "nak-ok-baep", meaning: "設計師", category: "職業" },
    { id: 292, thai: "ผู้จัดการ", pinyin: "phu-jud-kaan", meaning: "經理", category: "職業" },
    { id: 293, thai: "ช่างเสริมสวย", pinyin: "chang-serm-suay", meaning: "美髮師", category: "職業" },
    { id: 294, thai: "นักบัญชี", pinyin: "nak-ban-chee", meaning: "會計師", category: "職業" },
    { id: 295, thai: "ดีใจ", pinyin: "dee-jai", meaning: "開心", category: "情緒" },
    { id: 296, thai: "เสียใจ", pinyin: "sia-jai", meaning: "傷心", category: "情緒" },
    { id: 297, thai: "โกรธ", pinyin: "grot", meaning: "生氣", category: "情緒" },
    { id: 298, thai: "กลัว", pinyin: "glua", meaning: "害怕", category: "情緒" },
    { id: 299, thai: "ประหลาดใจ", pinyin: "pra-laat-jai", meaning: "驚訝", category: "情緒" },
    { id: 300, thai: "ภูมิใจ", pinyin: "phum-jai", meaning: "驕傲", category: "情緒" },
    { id: 301, thai: "กังวล", pinyin: "kang-won", meaning: "擔心", category: "情緒" },
    { id: 302, thai: "ตื่นเต้น", pinyin: "tuun-ten", meaning: "興奮", category: "情緒" },
    { id: 303, thai: "ผ่อนคลาย", pinyin: "phon-khlaai", meaning: "放鬆", category: "情緒" },
    { id: 304, thai: "เหงา", pinyin: "ngao", meaning: "寂寞", category: "情緒" },
    { id: 305, thai: "อิจฉา", pinyin: "it-chaa", meaning: "嫉妒", category: "情緒" },
    { id: 306, thai: "ละอาย", pinyin: "la-aai", meaning: "害羞", category: "情緒" },
    { id: 307, thai: "สับสน", pinyin: "sap-son", meaning: "困惑", category: "情緒" },
    { id: 308, thai: "ขี้เกียจ", pinyin: "khi-kiat", meaning: "懶惰", category: "情緒" },
    { id: 309, thai: "ขยัน", pinyin: "kha-yan", meaning: "勤奮", category: "情緒" },
    { id: 310, thai: "มีความหวัง", pinyin: "mee-khwam-wang", meaning: "有希望", category: "情緒" },
    { id: 311, thai: "หมดหวัง", pinyin: "mot-wang", meaning: "絕望", category: "情緒" },
    { id: 312, thai: "ประหม่า", pinyin: "pra-maa", meaning: "緊張", category: "情緒" },
    { id: 313, thai: "พอใจ", pinyin: "phor-jai", meaning: "滿意", category: "情緒" },
    { id: 314, thai: "เบิกบาน", pinyin: "boek-baan", meaning: "欣喜", category: "情緒" },
    { id: 315, thai: "โศกเศร้า", pinyin: "sok-sao", meaning: "悲傷", category: "情緒" },
    { id: 316, thai: "สงบ", pinyin: "sa-ngop", meaning: "平靜", category: "情緒" },
    { id: 317, thai: "หงุดหงิด", pinyin: "ngut-ngit", meaning: "煩躁", category: "情緒" },
    { id: 318, thai: "ไฟแรง", pinyin: "fai-raeng", meaning: "充滿幹勁", category: "情緒" },
    { id: 319, thai: "หัว", pinyin: "hua", meaning: "頭", category: "身體" },
    { id: 320, thai: "ใบหน้า", pinyin: "bai-naa", meaning: "臉", category: "身體" },
    { id: 321, thai: "ผม", pinyin: "phom", meaning: "頭髮", category: "身體" },
    { id: 322, thai: "ตา", pinyin: "taa", meaning: "眼睛", category: "身體" },
    { id: 323, thai: "หู", pinyin: "huu", meaning: "耳朵", category: "身體" },
    { id: 324, thai: "จมูก", pinyin: "ja-mook", meaning: "鼻子", category: "身體" },
    { id: 325, thai: "ปาก", pinyin: "paak", meaning: "嘴巴", category: "身體" },
    { id: 326, thai: "ฟัน", pinyin: "fan", meaning: "牙齒", category: "身體" },
    { id: 327, thai: "ลิ้น", pinyin: "lin", meaning: "舌頭", category: "身體" },
    { id: 328, thai: "คอ", pinyin: "kho", meaning: "脖子", category: "身體" },
    { id: 329, thai: "ไหล่", pinyin: "lai", meaning: "肩膀", category: "身體" },
    { id: 330, thai: "แขน", pinyin: "khaen", meaning: "手臂", category: "身體" },
    { id: 331, thai: "ข้อศอก", pinyin: "kho-sok", meaning: "手肘", category: "身體" },
    { id: 332, thai: "มือ", pinyin: "mue", meaning: "手", category: "身體" },
    { id: 333, thai: "นิ้ว", pinyin: "niu", meaning: "手指", category: "身體" },
    { id: 334, thai: "หน้าอก", pinyin: "na-ok", meaning: "胸部", category: "身體" },
    { id: 335, thai: "หลัง", pinyin: "lang", meaning: "背部", category: "身體" },
    { id: 336, thai: "ท้อง", pinyin: "thong", meaning: "肚子", category: "身體" },
    { id: 337, thai: "ขา", pinyin: "kha", meaning: "腿", category: "身體" },
    { id: 338, thai: "เข่า", pinyin: "khao", meaning: "膝蓋", category: "身體" },
    { id: 339, thai: "เท้า", pinyin: "tao", meaning: "腳", category: "身體" },
    { id: 340, thai: "นิ้วเท้า", pinyin: "niu-tao", meaning: "腳趾", category: "身體" },
    { id: 341, thai: "หัวใจ", pinyin: "hua-jai", meaning: "心臟", category: "身體" },
    { id: 342, thai: "สมอง", pinyin: "sa-mong", meaning: "大腦", category: "身體" },
    { id: 343, thai: "ผิว", pinyin: "phiu", meaning: "皮膚", category: "身體" },
    { id: 344, thai: "ปอด", pinyin: "pod", meaning: "肺", category: "身體" },
    { id: 345, thai: "ตับ", pinyin: "tab", meaning: "肝", category: "身體" },
    { id: 346, thai: "ไต", pinyin: "tai", meaning: "腎", category: "身體" },
    { id: 347, thai: "โต๊ะ", pinyin: "to", meaning: "桌子", category: "家庭" },
    { id: 348, thai: "เก้าอี้", pinyin: "kao-ii", meaning: "椅子", category: "家庭" },
    { id: 349, thai: "โซฟา", pinyin: "so-faa", meaning: "沙發", category: "家庭" },
    { id: 350, thai: "เตียง", pinyin: "tiang", meaning: "床", category: "家庭" },
    { id: 351, thai: "หมอน", pinyin: "mon", meaning: "枕頭", category: "家庭" },
    { id: 352, thai: "ผ้าห่ม", pinyin: "pha-hom", meaning: "棉被", category: "家庭" },
    { id: 353, thai: "พรม", pinyin: "phrom", meaning: "地毯", category: "家庭" },
    { id: 354, thai: "ตู้เย็น", pinyin: "tu-yen", meaning: "冰箱", category: "家庭" },
    { id: 355, thai: "เตาอบ", pinyin: "tao-ob", meaning: "烤箱", category: "家庭" },
    { id: 356, thai: "ไมโครเวฟ", pinyin: "mai-khro-wave", meaning: "微波爐", category: "家庭" },
    { id: 357, thai: "เครื่องซักผ้า", pinyin: "khruang-sak-pha", meaning: "洗衣機", category: "家庭" },
    { id: 358, thai: "เครื่องปรับอากาศ", pinyin: "khruang-prap-a-kat", meaning: "冷氣", category: "家庭" },
    { id: 359, thai: "พัดลม", pinyin: "phat-lom", meaning: "電扇", category: "家庭" },
    { id: 360, thai: "โทรทัศน์", pinyin: "tho-ra-that", meaning: "電視", category: "家庭" },
    { id: 361, thai: "รีโมต", pinyin: "ri-mot", meaning: "遙控器", category: "家庭" },
    { id: 362, thai: "โคมไฟ", pinyin: "khom-fai", meaning: "燈", category: "家庭" },
    { id: 363, thai: "นาฬิกา", pinyin: "na-li-gaa", meaning: "時鐘", category: "家庭" },
    { id: 364, thai: "จาน", pinyin: "jaan", meaning: "盤子", category: "家庭" },
    { id: 365, thai: "ชาม", pinyin: "chaam", meaning: "碗", category: "家庭" },
    { id: 366, thai: "ช้อน", pinyin: "chon", meaning: "湯匙", category: "家庭" },
    { id: 367, thai: "ส้อม", pinyin: "som", meaning: "叉子", category: "家庭" },
    { id: 368, thai: "มีด", pinyin: "mit", meaning: "刀", category: "家庭" },
    { id: 369, thai: "แก้ว", pinyin: "kaew", meaning: "杯子", category: "家庭" },
    { id: 370, thai: "กระทะ", pinyin: "kra-tha", meaning: "平底鍋", category: "家庭" },
    { id: 371, thai: "หม้อ", pinyin: "mor", meaning: "鍋子", category: "家庭" },
    { id: 372, thai: "ถังขยะ", pinyin: "thang-kha-ya", meaning: "垃圾桶", category: "家庭" },
    { id: 373, thai: "ไม้กวาด", pinyin: "mai-gwaa", meaning: "掃把", category: "家庭" },
    { id: 374, thai: "ที่ตักผง", pinyin: "thi-tak-phong", meaning: "畚箕", category: "家庭" },
    { id: 375, thai: "เรือ", pinyin: "ruea", meaning: "船", category: "交通" },
    { id: 376, thai: "เรือด่วน", pinyin: "ruea-duan", meaning: "快艇", category: "交通" },
    { id: 377, thai: "เรือเฟอร์รี", pinyin: "ruea-fer-ri", meaning: "渡輪", category: "交通" },
    { id: 378, thai: "เรือบรรทุก", pinyin: "ruea-ban-thuk", meaning: "貨船", category: "交通" },
    { id: 379, thai: "เรือหางยาว", pinyin: "ruea-hang-yao", meaning: "長尾船", category: "交通" },
    { id: 380, thai: "รถจักรยานยนต์", pinyin: "rot-jak-ka-yaan-yon", meaning: "機車", category: "交通" },
    { id: 381, thai: "รถบรรทุก", pinyin: "rot-ban-thuk", meaning: "卡車", category: "交通" },
    { id: 382, thai: "รถยนต์", pinyin: "rot-yon", meaning: "汽車", category: "交通" },
    { id: 383, thai: "รถสปอร์ต", pinyin: "rot-sa-port", meaning: "跑車", category: "交通" },
    { id: 384, thai: "รถตำรวจ", pinyin: "rot-tam-ruat", meaning: "警車", category: "交通" },
    { id: 385, thai: "รถพยาบาล", pinyin: "rot-pha-yaa-baan", meaning: "救護車", category: "交通" },
    { id: 386, thai: "รถดับเพลิง", pinyin: "rot-dap-ploeng", meaning: "消防車", category: "交通" },
    { id: 387, thai: "รถไฟใต้ดิน", pinyin: "rot-fai-tai-din", meaning: "地鐵", category: "交通" },
    { id: 388, thai: "รถราง", pinyin: "rot-raang", meaning: "路面電車", category: "交通" },
    { id: 389, thai: "เรือบิน", pinyin: "ruea-bin", meaning: "飛機", category: "交通" },
    { id: 390, thai: "เฮลิคอปเตอร์", pinyin: "he-li-khop-ter", meaning: "直升機", category: "交通" },
    { id: 391, thai: "เรือเหาะ", pinyin: "ruea-hor", meaning: "飛艇", category: "交通" },
    { id: 392, thai: "รถม้า", pinyin: "rot-maa", meaning: "馬車", category: "交通" },
    { id: 393, thai: "รถสามล้อ", pinyin: "rot-sam-law", meaning: "三輪車", category: "交通" },
    { id: 394, thai: "รถตุ๊กตุ๊ก", pinyin: "rot-tuk-tuk", meaning: "嘟嘟車", category: "交通" },
    { id: 395, thai: "แท็บเล็ต", pinyin: "thaeb-let", meaning: "平板", category: "科技" },
    { id: 396, thai: "สมาร์ตโฟน", pinyin: "smart-phon", meaning: "智慧型手機", category: "科技" },
    { id: 397, thai: "หูฟัง", pinyin: "hu-fang", meaning: "耳機", category: "科技" },
    { id: 398, thai: "ลำโพง", pinyin: "lam-phong", meaning: "喇叭", category: "科技" },
    { id: 399, thai: "กล้องถ่ายรูป", pinyin: "klong-thai-ruup", meaning: "相機", category: "科技" },
    { id: 400, thai: "เมาส์", pinyin: "mao", meaning: "滑鼠", category: "科技" },
    { id: 401, thai: "คีย์บอร์ด", pinyin: "khi-bord", meaning: "鍵盤", category: "科技" },
    { id: 402, thai: "หน้าจอ", pinyin: "na-jor", meaning: "螢幕", category: "科技" },
    { id: 403, thai: "โปรเจคเตอร์", pinyin: "pro-jek-ter", meaning: "投影機", category: "科技" },
    { id: 404, thai: "ดิจิทัลเพน", pinyin: "di-ji-ton-pen", meaning: "數位筆", category: "科技" },
    { id: 405, thai: "ฮาร์ดดิสก์", pinyin: "hard-disk", meaning: "硬碟", category: "科技" },
    { id: 406, thai: "แฟลชไดรฟ์", pinyin: "flash-drive", meaning: "隨身碟", category: "科技" },
    { id: 407, thai: "ไวไฟ", pinyin: "wai-fai", meaning: "無線網路", category: "科技" },
    { id: 408, thai: "คลาวด์", pinyin: "cloud", meaning: "雲端", category: "科技" },
    { id: 409, thai: "ซอฟต์แวร์", pinyin: "soft-ware", meaning: "軟體", category: "科技" },
    { id: 410, thai: "เฟิร์มแวร์", pinyin: "firm-ware", meaning: "韌體", category: "科技" },
    { id: 411, thai: "แอปพลิเคชัน", pinyin: "app-pli-khae-shan", meaning: "應用程式", category: "科技" },
    { id: 412, thai: "โค้ด", pinyin: "code", meaning: "程式碼", category: "科技" },
    { id: 413, thai: "บอต", pinyin: "bot", meaning: "機器人", category: "科技" },
    { id: 414, thai: "ภูเขา", pinyin: "phu-khao", meaning: "山", category: "自然" },
    { id: 415, thai: "แม่น้ำ", pinyin: "mae-nam", meaning: "河流", category: "自然" },
    { id: 416, thai: "ทะเล", pinyin: "tha-lay", meaning: "大海", category: "自然" },
    { id: 417, thai: "มหาสมุทร", pinyin: "ma-haa-sa-mut", meaning: "海洋", category: "自然" },
    { id: 418, thai: "ทะเลสาบ", pinyin: "tha-lay-saap", meaning: "湖泊", category: "自然" },
    { id: 419, thai: "น้ำตก", pinyin: "nam-tok", meaning: "瀑布", category: "自然" },
    { id: 420, thai: "ป่า", pinyin: "paa", meaning: "森林", category: "自然" },
    { id: 421, thai: "ทุ่งนา", pinyin: "thung-naa", meaning: "稻田", category: "自然" },
    { id: 422, thai: "ท้องฟ้า", pinyin: "thong-faa", meaning: "天空", category: "自然" },
    { id: 423, thai: "เมฆ", pinyin: "mek", meaning: "雲", category: "自然" },
    { id: 424, thai: "สายรุ้ง", pinyin: "saai-rung", meaning: "彩虹", category: "自然" },
    { id: 425, thai: "พระอาทิตย์", pinyin: "phra-aa-thit", meaning: "太陽", category: "自然" },
    { id: 426, thai: "พระจันทร์", pinyin: "phra-jan", meaning: "月亮", category: "自然" },
    { id: 427, thai: "ดาว", pinyin: "dao", meaning: "星星", category: "自然" },
    { id: 428, thai: "ลม", pinyin: "lom", meaning: "風", category: "自然" },
    { id: 429, thai: "ฝน", pinyin: "fon", meaning: "雨", category: "自然" },
    { id: 430, thai: "หิมะ", pinyin: "hi-ma", meaning: "雪", category: "自然" },
    { id: 431, thai: "ฟ้าผ่า", pinyin: "faa-pha", meaning: "閃電", category: "自然" },
    { id: 432, thai: "แผ่นดินไหว", pinyin: "phaen-din-wai", meaning: "地震", category: "自然" },
    { id: 433, thai: "คลื่น", pinyin: "khluen", meaning: "海浪", category: "自然" },
    { id: 434, thai: "หมอก", pinyin: "mok", meaning: "霧", category: "自然" },
    { id: 435, thai: "ดอกไม้", pinyin: "dok-mai", meaning: "花", category: "自然" },
    { id: 436, thai: "ต้นไม้", pinyin: "ton-mai", meaning: "樹", category: "自然" },
    { id: 437, thai: "ใบไม้", pinyin: "bai-mai", meaning: "樹葉", category: "自然" },
    { id: 438, thai: "ทราย", pinyin: "saai", meaning: "沙", category: "自然" },
    { id: 439, thai: "มหาวิทยาลัย", pinyin: "ma-haa-wit-tha-yaa-lai", meaning: "大學", category: "教育" },
    { id: 440, thai: "ห้องเรียน", pinyin: "hong-rian", meaning: "教室", category: "教育" },
    { id: 441, thai: "หนังสือเรียน", pinyin: "nang-seu-rian", meaning: "課本", category: "教育" },
    { id: 442, thai: "ดินสอ", pinyin: "din-sor", meaning: "鉛筆", category: "教育" },
    { id: 443, thai: "ยางลบ", pinyin: "yaang-lob", meaning: "橡皮擦", category: "教育" },
    { id: 444, thai: "กระเป๋านักเรียน", pinyin: "kra-pao-nak-rian", meaning: "書包", category: "教育" },
    { id: 445, thai: "การบ้าน", pinyin: "kaan-baan", meaning: "作業", category: "教育" },
    { id: 446, thai: "ตารางสอน", pinyin: "ta-raang-son", meaning: "課表", category: "教育" },
    { id: 447, thai: "สอบ", pinyin: "sop", meaning: "考試", category: "教育" },
    { id: 448, thai: "คะแนน", pinyin: "kha-naen", meaning: "成績", category: "教育" },
    { id: 449, thai: "ประกาศนียบัตร", pinyin: "pra-kat-ni-ya-bat", meaning: "證書", category: "教育" },
    { id: 450, thai: "วิชาคณิตศาสตร์", pinyin: "wi-chaa-kha-nit-sat", meaning: "數學", category: "教育" },
    { id: 451, thai: "วิชาวิทยาศาสตร์", pinyin: "wi-chaa-wit-tha-ya-sat", meaning: "自然", category: "教育" },
    { id: 452, thai: "วิชาภาษาไทย", pinyin: "wi-chaa-pha-saa-thai", meaning: "泰文課", category: "教育" },
    { id: 453, thai: "วิชาภาษาอังกฤษ", pinyin: "wi-chaa-pha-saa-ang-grit", meaning: "英文課", category: "教育" },
    { id: 454, thai: "ห้องสมุด", pinyin: "hong-sa-mut", meaning: "圖書館", category: "教育" },
    { id: 455, thai: "สนามกีฬา", pinyin: "sa-nam-kii-laa", meaning: "運動場", category: "教育" },
    { id: 456, thai: "ชมรม", pinyin: "chom-rom", meaning: "社團", category: "教育" },
    { id: 457, thai: "ทุนการศึกษา", pinyin: "thun-kaan-suek-saa", meaning: "獎學金", category: "教育" },
    { id: 458, thai: "ปริญญา", pinyin: "pa-rin-yaa", meaning: "學位", category: "教育" },
    { id: 459, thai: "ปฐมวัย", pinyin: "pa-thom-wai", meaning: "幼兒教育", category: "教育" },
    { id: 460, thai: "มัธยม", pinyin: "mat-tha-yom", meaning: "中學", category: "教育" },
    { id: 461, thai: "อาจารย์", pinyin: "aa-jaan", meaning: "教授", category: "教育" },
    { id: 462, thai: "วิทยาเขต", pinyin: "wit-tha-yaa-khet", meaning: "校區", category: "教育" },
    { id: 463, thai: "ผัดไทย", pinyin: "phat-thai", meaning: "泰式炒河粉", category: "料理" },
    { id: 464, thai: "ต้มยำกุ้ง", pinyin: "tom-yum-gung", meaning: "冬蔭功", category: "料理" },
    { id: 465, thai: "แกงเขียวหวาน", pinyin: "gaeng-khiao-wan", meaning: "綠咖哩", category: "料理" },
    { id: 466, thai: "ส้มตำ", pinyin: "som-tam", meaning: "青木瓜沙拉", category: "料理" },
    { id: 467, thai: "ข้าวมันไก่", pinyin: "khao-man-gai", meaning: "海南雞飯", category: "料理" },
    { id: 468, thai: "ข้าวผัด", pinyin: "khao-phat", meaning: "炒飯", category: "料理" },
    { id: 469, thai: "ต้มข่าไก่", pinyin: "tom-kha-gai", meaning: "椰奶雞湯", category: "料理" },
    { id: 470, thai: "ลาบ", pinyin: "laap", meaning: "東北辣拌", category: "料理" },
    { id: 471, thai: "น้ำพริก", pinyin: "nam-phrik", meaning: "辣醬", category: "料理" },
    { id: 472, thai: "ไข่เจียว", pinyin: "khai-jiao", meaning: "煎蛋", category: "料理" },
    { id: 473, thai: "ไข่ดาว", pinyin: "khai-dao", meaning: "荷包蛋", category: "料理" },
    { id: 474, thai: "หมูกระทะ", pinyin: "muu-gra-tha", meaning: "燒肉火鍋", category: "料理" },
    { id: 475, thai: "หมูปิ้ง", pinyin: "muu-bping", meaning: "烤豬肉串", category: "料理" },
    { id: 476, thai: "ไก่ทอด", pinyin: "gai-thot", meaning: "炸雞", category: "料理" },
    { id: 477, thai: "เนื้อย่าง", pinyin: "nuea-yang", meaning: "烤牛肉", category: "料理" },
    { id: 478, thai: "ปลาทอด", pinyin: "plaa-thot", meaning: "炸魚", category: "料理" },
    { id: 479, thai: "ก๋วยเตี๋ยว", pinyin: "guai-tiao", meaning: "米粉湯", category: "料理" },
    { id: 480, thai: "ขนมจีน", pinyin: "kha-nom-jeen", meaning: "米線", category: "料理" },
    { id: 481, thai: "ข้าวเหนียวมะม่วง", pinyin: "khao-niao-ma-muang", meaning: "芒果糯米", category: "料理" },
    { id: 482, thai: "ข้าวต้ม", pinyin: "khao-tom", meaning: "白粥", category: "料理" },
    { id: 483, thai: "ข้าวแกง", pinyin: "khao-gaeng", meaning: "泰式便當", category: "料理" },
    { id: 484, thai: "แกงพะแนง", pinyin: "gaeng-pha-naeng", meaning: "帕能咖哩", category: "料理" },
    { id: 485, thai: "ผัดกะเพรา", pinyin: "phat-kra-phrao", meaning: "打拋", category: "料理" },
    { id: 486, thai: "ผัดซีอิ๊ว", pinyin: "phat-see-iew", meaning: "醬油炒麵", category: "料理" },
    { id: 487, thai: "ผัดขี้เมา", pinyin: "phat-khi-mao", meaning: "醉翁炒麵", category: "料理" },
    { id: 488, thai: "ข้าวหมูแดง", pinyin: "khao-muu-daeng", meaning: "叉燒飯", category: "料理" },
    { id: 489, thai: "ข้าวขาหมู", pinyin: "khao-kha-muu", meaning: "豬腳飯", category: "料理" },
    { id: 490, thai: "ข้าวหมูกรอบ", pinyin: "khao-muu-krop", meaning: "脆皮豬飯", category: "料理" },
    { id: 491, thai: "ยำทะเล", pinyin: "yam-tha-lay", meaning: "海鮮涼拌", category: "料理" },
    { id: 492, thai: "ยำวุ้นเส้น", pinyin: "yam-woon-sen", meaning: "粉絲涼拌", category: "料理" },
    { id: 493, thai: "ซุปหน่อไม้", pinyin: "sup-nor-mai", meaning: "竹筍湯", category: "料理" },
    { id: 494, thai: "ซุปกระดูก", pinyin: "sup-kra-duuk", meaning: "骨湯", category: "料理" },
    { id: 495, thai: "โจ๊ก", pinyin: "jok", meaning: "稀飯", category: "料理" },
    { id: 496, thai: "บะหมี่", pinyin: "ba-mee", meaning: "蛋麵", category: "料理" },
    { id: 497, thai: "ซูชิ", pinyin: "su-shi", meaning: "壽司", category: "料理" },
    { id: 498, thai: "พิซซ่า", pinyin: "phit-saa", meaning: "披薩", category: "料理" },
    { id: 499, thai: "แซนด์วิช", pinyin: "saen-wich", meaning: "三明治", category: "料理" },
    { id: 500, thai: "ฮอทดอก", pinyin: "hot-dok", meaning: "熱狗", category: "料理" },
  ];

  const consonantData = [
    { char: "ก", name: "ko kai", class: "mid", meaning: "雞" },
    { char: "ข", name: "kho khai", class: "high", meaning: "蛋" },
    { char: "ฃ", name: "kho khuat", class: "high", meaning: "瓶" },
    { char: "ค", name: "kho khwai", class: "low", meaning: "水牛" },
    { char: "ฅ", name: "kho khon", class: "low", meaning: "人" },
    { char: "ฆ", name: "kho ra-khang", class: "low", meaning: "鐘" },
    { char: "ง", name: "ngo ngu", class: "low", meaning: "蛇" },
    { char: "จ", name: "jo jan", class: "mid", meaning: "盤子" },
    { char: "ฉ", name: "cho ching", class: "high", meaning: "鈸" },
    { char: "ช", name: "cho chang", class: "low", meaning: "大象" },
    { char: "ซ", name: "so so", class: "low", meaning: "鎖鏈" },
    { char: "ฌ", name: "cho choe", class: "low", meaning: "樹" },
    { char: "ญ", name: "yo ying", class: "low", meaning: "女人" },
    { char: "ด", name: "do dek", class: "mid", meaning: "小孩" },
    { char: "ต", name: "to tao", class: "mid", meaning: "烏龜" },
    { char: "ถ", name: "tho thung", class: "high", meaning: "袋子" },
    { char: "ท", name: "tho thahan", class: "low", meaning: "士兵" },
    { char: "ธ", name: "tho thong", class: "low", meaning: "旗" },
    { char: "น", name: "no nu", class: "low", meaning: "老鼠" },
    { char: "บ", name: "bo baimai", class: "mid", meaning: "葉子" },
    { char: "ป", name: "po pla", class: "mid", meaning: "魚" },
    { char: "ผ", name: "pho phueng", class: "high", meaning: "蜜蜂" },
    { char: "ฝ", name: "fo fa", class: "high", meaning: "蓋子" },
    { char: "พ", name: "pho phan", class: "low", meaning: "盤子" },
    { char: "ฟ", name: "fo fan", class: "low", meaning: "牙齒" },
    { char: "ภ", name: "pho sam-phao", class: "low", meaning: "帆船" },
    { char: "ม", name: "mo ma", class: "low", meaning: "馬" },
    { char: "ย", name: "yo yak", class: "low", meaning: "巨人" },
    { char: "ร", name: "ro ruea", class: "low", meaning: "船" },
    { char: "ล", name: "lo ling", class: "low", meaning: "猴子" },
    { char: "ว", name: "wo waen", class: "low", meaning: "戒指" },
    { char: "ศ", name: "so sala", class: "high", meaning: "涼亭" },
    { char: "ษ", name: "so rue-si", class: "high", meaning: "隱士" },
    { char: "ส", name: "so suea", class: "high", meaning: "老虎" },
    { char: "ห", name: "ho hip", class: "high", meaning: "箱子" },
    { char: "ฬ", name: "lo chu-la", class: "low", meaning: "風箏" },
    { char: "อ", name: "o ang", class: "mid", meaning: "盆" },
    { char: "ฮ", name: "ho nok-huk", class: "low", meaning: "貓頭鷹" }
  ];

  const vowelData = [
    { char: "-ะ", name: "sara a", type: "short" },
    { char: "-า", name: "sara aa", type: "long" },
    { char: "อิ", name: "sara i", type: "short" },
    { char: "อี", name: "sara ii", type: "long" },
    { char: "อึ", name: "sara ue", type: "short" },
    { char: "อื", name: "sara uue", type: "long" },
    { char: "อุ", name: "sara u", type: "short" },
    { char: "อู", name: "sara uu", type: "long" },
    { char: "เ-ะ", name: "sara e", type: "short" },
    { char: "เ-", name: "sara ee", type: "long" },
    { char: "แ-ะ", name: "sara ae", type: "short" },
    { char: "แ-", name: "sara aae", type: "long" },
    { char: "โ-ะ", name: "sara o", type: "short" },
    { char: "โ-", name: "sara oo", type: "long" },
    { char: "เ-าะ", name: "sara or", type: "short" },
    { char: "-อ", name: "sara oor", type: "long" },
    { char: "เ-อะ", name: "sara oe", type: "short" },
    { char: "เ-อ", name: "sara ooe", type: "long" },
    { char: "เ-ียะ", name: "sara ia (短)", type: "short" },
    { char: "เ-ีย", name: "sara iia (長)", type: "long" },
    { char: "เ-ือะ", name: "sara uea (短)", type: "short" },
    { char: "เ-ือ", name: "sara uuea (長)", type: "long" },
    { char: "อัวะ", name: "sara ua (短)", type: "short" },
    { char: "อัว", name: "sara uua (長)", type: "long" },
    { char: "ำ", name: "sara am", type: "special" },
    { char: "ใ", name: "mai muan (ai)", type: "special" },
    { char: "ไ", name: "mai malai (ai)", type: "special" },
    { char: "เ-า", name: "sara ao", type: "special" }
  ];

  return { rawVocabData, consonantData, vowelData };
})();

